# Generated by Django 4.2.2 on 2023-07-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment_likes_comment_user_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
