# Generated by Django 4.2.2 on 2023-07-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_image'),
        ('post', '0005_remove_comment_user'),
    ]

    operations = [
    ]
