# Generated by Django 4.2.2 on 2023-07-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_merge_20230709_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='popularity',
        ),
    ]
