# Generated by Django 4.2.2 on 2023-07-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_image_alter_post_updated_at'),
        ('post', '0006_merge_0004_alter_post_image_0005_remove_comment_user'),
    ]

    operations = [
    ]
