# Generated by Django 4.2.2 on 2023-07-13 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_merge_0004_alter_post_image_0005_remove_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reposted_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Репост',
                'verbose_name_plural': 'Репосты',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='repost_set',
            field=models.ManyToManyField(related_name='reposted_posts', through='post.Repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
