# Generated by Django 4.2.2 on 2023-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_merge_20230713_0523'),
        ('post', '0007_repost_post_repost_set'),
    ]

    operations = [
    ]
