# Generated by Django 4.2.2 on 2023-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_markbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='markbooks',
            new_name='bookmarks',
        ),
    ]
